services:
  postgresql:
    image: bitnami/postgresql:latest
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=todolist
    ports:
      - "5432:5432"
